language: python

cache: pip

matrix:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27

    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.6
      env: TOXENV=py36

    - os: linux
      python: 3.7
      env: TOXENV=py37

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.7
      env: TOXENV=cov
      after_success:
        - coveralls

    - os: osx
      language: generic
      env: TOXENV=py37

install:
  - travis_retry bash -x .travis/install.sh

script:
  - tox

notifications:
  slack:
    secure: NksnLSqhN90VVFFpngTlH9nJD/szRjasmLT/9WlNXl+du2t6rTVK72E0PCNQsY0HQDWkZ1GsSSpXbAjRie6TdrvbpGPh2aHDYLjqr08eKpXGVtHW7HvAw8kmBDjj1jOEseS3TX3dCSlj2XRxzaBIcIlBa/CflcfRFoHt/9YPAvzyTYO6vzjrN0mwhGc6/4sUMrtvwdn8KHdAu/gJ+0WDeYUHRTVkaPR4ekPQMJ1L6tF6VN7gF8WKxxuDyg6I7bgspL4ZjgM/FjXP7SjwkP7AIfiAIe6iigzjhrTC3uj4tMpqGB3vC6Swvy+tPnjN3ki73DzBpc1l5k/iAIDxL+VFl+y1Xs5OA8rvSM02gePEgv6uf1r0k52/WSbf/AfowDoJDO7sSbKTn+ic+h5ZSMLnz9Z3avPf1kleK+jGNw3No7OSw+fP2xZ7S0NfueAl2sdbF152snhbMXgTG6alv26wfNCqpqWI6Tm2RkcPjc/e7V2wl4ky18fhthyP8Kfhb/iEnAGi8J2Cfd1Oyh7xx5C8VwTeStf+GeUVbYxg9sWdTFSPbqRzKaiR4avf41Wcjz4/zfUOsvq0w0QQhaYEs31CT8Han4KpX79LbrrAMfKTDBKyFRv0En1ka9LxIzposprDR4lcgeBjRrfDJSndoB2P3V9JIm0nQeTFkS70uyMy69A=
