language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.3
      env: TOXENV=python3.3
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6

os:
    - linux

install:
    - pip install tox
    - pip install coveralls

script: 
    - tox
    - python setup.py test --addopts "-v --cov mbstrdecoder --cov-report term-missing"

after_success:
    - coveralls

notifications:
   slack:
     secure: JKS665dRINC9PYtjDkn3Zsf/38G6+xmfyKa95ZdT5rFmaGsXN90BWmiupFaA5iCZh7wx8KYPEmX61J77MstIkibFhGJkpkH7TqmK/8Pqc97HB6PlX/5OhFjazJQkgXfGxOMTiQbSFlM43zu4elWtJxbVhWpX6x1Ik2i5nnsOHcbIHt     24 WqAGiE9e6cJHIk3ZA3Ysf2nyH1FZXc9UNMcV5TCUkk8Jt91Bg49JJISv83w1Cx33FoG5FLZglZrNpaWplGFH4KieHD57FRGPrQLZEt78FVMud3T69zt93FgWmdYmkBZtHWrcG4v7zXiBm4suA5tBzxED6N0xWrNnJ2jVlkyfv/yU8z1m4BkMDpEEZx     24 Uy6gezDZZmuLK1E3zqbmdQvYonzui/K4xVoJs7A9jYNd+uVRCVipaWAFGLvDglyavMrv+0XHHKZ7RdlK/zPqkUjUq5YIPtxTMhihElJ0g4HrAOIg4gktEjy5ev7uVC2V1ymPvdm6svotNPirI7DKdZqx3SiX7p96CqpPbwmBDgbLqXNOP0GDiIQxEr     24 D0ZUUIbmTs2zKiuax+05P+NHoD5UhW8OAgZsoRoCuvj7CtXLVhSB4vgCaLeG4Eq7Cza13BplJCrXMOu7EVwk4etlSIP/vx+0lqOXb21Tj4yVg4NYzOdemO05kGOLfZKwBiVNSzbyA=

deploy:
  provider: pypi
  user: vmmhypervisor
  password:
    secure: m7bj1mNED936fCmKmWHBiHx/mjehGU22YronFqDk3D0mNV7xebFwDRbKq5D45w0DhkN6chdJZ9gXf8HQxUjGr/4EdxUFKgYATwefK0bCvNH59MrT6V+17MbZcjElTWZSsnQc1o68yg2ZYnqu7cvMIotPyrP0UmE/51z9JlmBNCPW1lNoxWvJxxPwK3YtJyLjUuQQRNVJ7j6KtFw/4HWihr524t/XwA0PT+8dBmAFUN/Esm4RxKFjWrx/u1XnosDNXB+8HLuIwQTs5vwqkpE02MSf9jbi4vJyEdkCg9NDqyp+li4CWERQKdfS1fuKFqfyTjSnmqA5YwwXxTW4ZBEkKH/hQ/7rskpY2iA3ITgevl2nZtVUzeGotO68z5Nu+5RsOUilivT3d3TkJ7pyp0dz3b0i2D3NKtdl87v8n+W5kyG3sgjeQPyR+KT9YEEpboINKQY+zJp9dfy48DSliWIGAWcyhcoz9DG0tMcTZnXRX+/tn4idT+4xekZgHR7KkPlFMjrrov/estGYnHb6HGqTV0tCLL/nENMzNyWLE7pGkspb32dEP+26dhN3ke7uVya3Z8bGx+SwO0i7l0sLtbTasThKnQ37fjgdqd5mAfYZX9wHP/91rBPzpn6TX5oBOoM9jCJTcLI5MzlO+Lu01/wdMAHuowJnNO69Y/4jgUgMydc=
  on:
    tags: true
    repo: thombashi/mbstrdecoder
  distributions: "sdist bdist_wheel"
